<FLIGHTPLAN>
	<OriginAirport>LKMT</OriginAirport>
	<DestinationAirport>LKTB</DestinationAirport>
	<ROUTE>
		<LEGS>
			<Route_Waypoint>
				<Name>WPT1</Name>
				<Type>Normal</Type>
				<Latitude>49.483293</Latitude>
				<Longitude>17.337799</Longitude>
				<Speed>0</Speed>
				<Altitude>0</Altitude>
				<AltitudeCons>0</AltitudeCons>
				<AltitudeRestriction>none</AltitudeRestriction>
			</Route_Waypoint>
		</LEGS>
	</ROUTE>
</FLIGHTPLAN>
